spring:
  rabbitmq:
    host: 192.168.17.133
    port: 5672
    username: admin
    password: 1111
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual
      direct:
        acknowledge-mode: manual